User.create!(name: 'a', email: 'test1@gmail.com', password: 'aaaaaa', password_confirmation: 'aaaaaa')
User.create!(name: 'b', email: 'test2@gmail.com', password: 'aaaaaa', password_confirmation: 'aaaaaa')
User.create!(name: 'c', email: 'test3@gmail.com', password: 'aaaaaa', password_confirmation: 'aaaaaa')
User.create!(name: 'd', email: 'test4@gmail.com', password: 'aaaaaa', password_confirmation: 'aaaaaa')
User.create!(name: 'e', email: 'test5@gmail.com', password: 'aaaaaa', password_confirmation: 'aaaaaa')

book1 = Book.create!(id: 1, name: 'Reactハンズオンラーニング', author: 'Alex Banks', publication_date: 20210806, stock: 5, price: 3740)
book1.image.attach(io: File.open(Rails.root.join('../../book_app/backend/assets/images/React.jpg')), filename: 'React.jpg')
book2 = Book.create!(id: 2, name: 'Vue.js入門', author: '川口 和也', publication_date: 20180922, stock: 3, price: 3718)
book2.image.attach(io: File.open(Rails.root.join('../../book_app/backend/assets/images/Vue.jpg')), filename: 'Vue.jpg')
book3 = Book.create!(id: 3, name: 'Programming TypeScript', author: 'Boris Cherny ', publication_date: 20190521, stock: 6, price: 4200)
book3.image.attach(io: File.open(Rails.root.join('../../book_app/backend/assets/images/Typescript.jpg')), filename: 'Typescript.jpg')
book4 = Book.create!(id: 4, name: 'Ruby on Rails 6 実践ガイド', author: '黒田 努', publication_date:  20191220, stock: 2, price: 3850)
book4.image.attach(io: File.open(Rails.root.join('../../book_app/backend/assets/images/Rails.jpg')), filename: 'Rails.jpg')
book5 = Book.create!(id: 5, name: 'Python基礎&実践プログラミング', author: 'Magnus Lie Hetland', publication_date: 20200221, stock: 0, price: 3960)
book5.image.attach(io: File.open(Rails.root.join('../../book_app/backend/assets/images/Python.jpg')), filename: 'Python.jpg')
